name: update

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: Package name
        required: true
        type: string
      version:
        description: New version of the package (tag name)
        required: true
        type: string

# Grant write permissions to create pull requests
permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install beautifulsoup4 build
    - name: Run Action
      env:
        PKG_ACTION: UPDATE
        PKG_NAME: ${{ inputs.package_name }}
        PKG_VERSION: ${{ inputs.version }}
      run: |
        python .github/actions.py 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: ':package: [:robot:] Update package in PyPi index'
        title: '[🤖] Update `${{ inputs.package_name }}` in PyPi index'
        body: Automatically generated PR, updating `${{ inputs.package_name }}` in PyPi
          index.
        branch: update-${{ inputs.package_name }}-${{ github.run_number }}
        delete-branch: true
